"""added password field

Revision ID: 47077899a7db
Revises: a3b585a2869c
Create Date: 2021-07-02 10:25:56.613958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47077899a7db'
down_revision = 'a3b585a2869c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
